### PR TITLE
Fix #217 error with duplicate queries log 

### LINKED ISSUE #217: Error with new feature to log duplicate queries
**Describe the bug**
After enabling the new feature to send duplicate queries to ray #216  , i got this exception:
```
Object of class DateTime could not be converted to string
Pipeline.php:49
```

**Versions**

spatie/laravel-ray                             1.26.0 
spatie/ray                                     1.30.2 
ray Version 1.17.1 (1.17.1)

PHP version:
Laravel version: 8

**To Reproduce**
Linked to a query with $currentDate as DateTime

$currentDate = new \DateTime($datetime->format('Y-m-d'));
$model->where('date','>', $currentDate)

### PR DESCRIPTION
**Pull request by fabio-ivona**
Hi @freekmurze,

This pr will fix #217 by adding an handler for unsupported types in query parameters bindings

Also tests have been updated to address this issue

Thanks for your great work!

### CODE REVIEW

File: src/Watchers/DuplicateQueryWatcher.php [hunk 1]
```diff
@@ -43,6 +43,17 @@ public function register(): void
         });
     }
 
+    private function cleanupBindings(array $bindings): array
+    {
+        return array_map(function ($binding) {
+            if ($binding instanceof \DateTime) {
```
Comment (abenerd) [inline src/Watchers/DuplicateQueryWatcher.php:49]: Maybe check for the `DateTimeInterface` instead in case people use immutable dates, currently this case would not be caught by this.

Comment (fabio-ivona) [reply src/Watchers/DuplicateQueryWatcher.php:49]: @abenerd you're right! I'm pushing a commit to fix this

**Comment by freekmurze** [comment]
Thanks!

**Comment by masterix21** [comment]
I'm sorry for the issue. Thanks for the fix @fabio-ivona
